import { Anime } from './types';

export const mockAnimeList: Anime[] = [
  {
    id: '1',
    title: '강철의 연금술사',
    titleJa: '鋼の錬金術師',
    thumbnail: 'https://placehold.co/150x200/1a1a1a/white?text=FMA',
    year: 2009,
    season: 'Spring',
  },
  {
    id: '2',
    title: '스즈메의 문단속',
    titleJa: 'すずめの戸締まり',
    thumbnail: 'https://placehold.co/150x200/2a4a6a/white?text=Suzume',
    year: 2022,
    season: 'Fall',
  },
  {
    id: '3',
    title: '귀멸의 칼날',
    titleJa: '鬼滅の刃',
    thumbnail: 'https://placehold.co/150x200/4a1a2a/white?text=Demon',
    year: 2019,
    season: 'Spring',
  },
  {
    id: '4',
    title: '진격의 거인',
    titleJa: '進撃の巨人',
    thumbnail: 'https://placehold.co/150x200/3a2a1a/white?text=AOT',
    year: 2013,
    season: 'Spring',
  },
  {
    id: '5',
    title: '주술회전',
    titleJa: '呪術廻戦',
    thumbnail: 'https://placehold.co/150x200/1a3a4a/white?text=JJK',
    year: 2020,
    season: 'Fall',
  },
  {
    id: '6',
    title: '체인소 맨',
    titleJa: 'チェンソーマン',
    thumbnail: 'https://placehold.co/150x200/5a1a1a/white?text=CSM',
    year: 2022,
    season: 'Fall',
  },
  {
    id: '7',
    title: '스파이 패밀리',
    titleJa: 'SPY×FAMILY',
    thumbnail: 'https://placehold.co/150x200/2a5a3a/white?text=SPY',
    year: 2022,
    season: 'Spring',
  },
  {
    id: '8',
    title: '원피스',
    titleJa: 'ワンピース',
    thumbnail: 'https://placehold.co/150x200/4a3a1a/white?text=OP',
    year: 1999,
    season: 'Fall',
  },
  {
    id: '9',
    title: '나루토',
    titleJa: 'NARUTO',
    thumbnail: 'https://placehold.co/150x200/5a4a2a/white?text=Naruto',
    year: 2002,
    season: 'Fall',
  },
  {
    id: '10',
    title: '헌터×헌터',
    titleJa: 'HUNTER×HUNTER',
    thumbnail: 'https://placehold.co/150x200/2a4a2a/white?text=HxH',
    year: 2011,
    season: 'Fall',
  },
  {
    id: '11',
    title: '바이올렛 에버가든',
    titleJa: 'ヴァイオレット・エヴァーガーデン',
    thumbnail: 'https://placehold.co/150x200/3a3a5a/white?text=Violet',
    year: 2018,
    season: 'Winter',
  },
  {
    id: '12',
    title: '던전밥',
    titleJa: 'ダンジョン飯',
    thumbnail: 'https://placehold.co/150x200/5a3a2a/white?text=Dungeon',
    year: 2024,
    season: 'Winter',
  },
  {
    id: '13',
    title: '프리렌',
    titleJa: '葬送のフリーレン',
    thumbnail: 'https://placehold.co/150x200/2a3a5a/white?text=Frieren',
    year: 2023,
    season: 'Fall',
  },
  {
    id: '14',
    title: '86',
    titleJa: '86-エイティシックス-',
    thumbnail: 'https://placehold.co/150x200/4a2a3a/white?text=86',
    year: 2021,
    season: 'Spring',
  },
  {
    id: '15',
    title: '리제로',
    titleJa: 'Re:ゼロから始める異世界生活',
    thumbnail: 'https://placehold.co/150x200/3a2a4a/white?text=ReZero',
    year: 2016,
    season: 'Spring',
  },
  {
    id: '16',
    title: '노 게임 노 라이프',
    titleJa: 'ノーゲーム・ノーライフ',
    thumbnail: 'https://placehold.co/150x200/5a2a5a/white?text=NGNL',
    year: 2014,
    season: 'Spring',
  },
  {
    id: '17',
    title: '오버로드',
    titleJa: 'オーバーロード',
    thumbnail: 'https://placehold.co/150x200/1a1a3a/white?text=Overlord',
    year: 2015,
    season: 'Summer',
  },
  {
    id: '18',
    title: '이 멋진 세계에 축복을',
    titleJa: 'この素晴らしい世界に祝福を',
    thumbnail: 'https://placehold.co/150x200/2a5a5a/white?text=Konosuba',
    year: 2016,
    season: 'Winter',
  },
  {
    id: '19',
    title: '무직전생',
    titleJa: '無職転生',
    thumbnail: 'https://placehold.co/150x200/4a4a2a/white?text=Mushoku',
    year: 2021,
    season: 'Winter',
  },
  {
    id: '20',
    title: '전생했더니 슬라임이었던 건에 대하여',
    titleJa: '転生したらスライムだった件',
    thumbnail: 'https://placehold.co/150x200/2a3a6a/white?text=Slime',
    year: 2018,
    season: 'Fall',
  },
];
